name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-x86_64:
    runs-on: x86_64
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
    - name: Install docker
      run:
        apt-get update --yes
        apt-get install --yes ca-certificates curl gnupg


    - name: build application
      run: make container-image/build CONTAINER_RUNTIME=docker